# frozen_string_literal: true

# Deterministic verification of a Rails workspace.
# Run both from the workflow and standalone (bin/verify-workspace).

require "fileutils"
require "json"
require "shellwords"
require_relative "route_smoke"
require_relative "verify_report"

module VerifyRevision
  # Five checks, none dead and none dominated by another (reworked 2026-09-06):
  #   bundle_check   — lockfile satisfied; the only short-circuit (see run)
  #   db_prepare     — full boot + migrations; also writes db/schema.rb, which
  #                    the test env's maintain_test_schema! needs for the two
  #                    Minitest-based checks that follow
  #   zeitwerk_check — eager-loads every app/ file: the only check that sees
  #                    code no route and no test touches (syntax errors,
  #                    constants missing at class-body level, filename/constant
  #                    mismatches)
  #   route_smoke    — requests every static GET page in the test env;
  #                    advisory (see ADVISORY). Catches what db:prepare,
  #                    zeitwerk and an untested action all miss: a page that
  #                    raises at request time. After zeitwerk_check because a
  #                    load error is a clearer message than the same failure
  #                    surfacing as a raising page
  #   rails_test     — the app's own suite, when it has one
  # boot_check (`rails runner "puts :ok"`) was removed as dominated: db_prepare
  # boots the same app, first. herb_lint never ran (herb is not in the
  # skeleton) and was evaluated and rejected — the as-built note in
  # docs/02-architecture/01-workflows-and-decisions.md records why.
  CHECKS = %i[bundle_check db_prepare zeitwerk_check route_smoke rails_test].freeze

  # Checks whose failure triggers remediation but does not block the commit.
  # route_smoke is advisory: one raising page among many is not a reason to
  # throw away the whole revision and the ones queued after it. It still enters
  # W2.AR / W2.R with the exact exception in the fix prompt; if that doesn't
  # resolve it, the revision commits with the failure recorded in the verify
  # sentinel — which is what happened before the check existed, minus the fix
  # attempt. zeitwerk_check stays blocking: an orphan file that won't load is
  # agent garbage with a trivial fix.
  ADVISORY = %i[route_smoke].freeze

  # One line per check, prepended to its output in the fix prompt. Minitest ends
  # a failure with "bin/rails test tmp/hifumi/route_smoke_test.rb:8" — a re-run
  # hint for a file this module deletes on exit. Without this the fix agent goes
  # looking for it.
  HINTS = {
    route_smoke: "hifumi requested every static GET page of the app in the test environment; " \
                 "the pages below raised or returned 5xx. The test file under tmp/hifumi/ is " \
                 "generated by the verifier and removed afterwards — it is not part of the app. " \
                 "Fix the controller, view or model; do not look for, recreate or edit tmp/hifumi/."
  }.freeze

  # Copied into the workspace for one run and removed again. Removed rather than
  # left to .gitignore because four April-era workspaces predate the skeleton's
  # /tmp/* rule and W2.5's `git add -A` would commit them.
  ROUTE_SMOKE_DIR   = "tmp/hifumi"
  ROUTE_SMOKE_FILES = { "route_smoke.rb" => "route_smoke.rb", "route_smoke_check.rb" => "route_smoke_test.rb" }.freeze

  # Short-circuit on bundle_check failure: every later check (db_prepare,
  # zeitwerk_check, route_smoke, rails_test) loads bundler and would emit the same
  # Bundler::GemNotFound stacktrace. Surfacing all four padded the fix-agent
  # prompt with 4× the same noise, costing input tokens with zero new info.
  def self.run(workspace, known_failing_routes: [])
    results = []
    CHECKS.each do |check|
      result = perform(check, workspace, known_failing_routes: known_failing_routes)
      next if result.nil?

      results << result
      if check == :bundle_check && !result[:passed]
        break # bundle_check is the foundation — nothing downstream can succeed without it.
      end
    end

    {
      checks: results,
      passed: results.select { |r| r[:passed] },
      failed: results.reject { |r| r[:passed] }
    }
  end

  # One check, same result shape as run. Used by bin/verify-workspace --check and
  # by the W2.B baseline.
  def self.run_one(check, workspace, known_failing_routes: [])
    result = perform(check, workspace, known_failing_routes: known_failing_routes)
    checks = [ result ].compact
    { checks: checks, passed: checks.select { |r| r[:passed] }, failed: checks.reject { |r| r[:passed] } }
  end

  def self.failed?(result)
    result[:failed].any?
  end

  def self.blocking_failed?(result)
    result[:failed].any? { |c| !ADVISORY.include?(c[:check]) }
  end

  # format_errors feeds agent(:fix) verbatim. A single check has been measured at
  # 9 374 chars (`rails test` with every action broken); three failing checks in
  # one run, times up to three fix prompts, is real money. Head-and-tail rather
  # than head-only because `rails test` puts its run/failure/error counts on the
  # last line — the same reason StatCap preserves the git-stat summary.
  ERROR_CAP_CHARS  = 4_000
  ERROR_TAIL_CHARS = 1_000

  def self.cap_error(output)
    # scrub: a generated app's test output is arbitrary bytes, and JSON.generate
    # (the sentinel below) raises on invalid UTF-8. A logging failure must not
    # abort the verify cog.
    text = output.to_s.dup.force_encoding(Encoding::UTF_8).scrub
    return text if text.length <= ERROR_CAP_CHARS

    head = text[0, ERROR_CAP_CHARS - ERROR_TAIL_CHARS]
    tail = text[-ERROR_TAIL_CHARS..]
    "#{head}\n[... #{text.length - ERROR_CAP_CHARS} chars truncated ...]\n#{tail}"
  end

  def self.format_errors(result)
    result[:failed].map do |c|
      [ "#{c[:name]}:", HINTS[c[:check]], cap_error(c[:output]) ].compact.join("\n")
    end.join("\n\n---\n\n")
  end

  def self.summary(result)
    result[:checks].map do |c|
      "#{c[:passed] ? 'PASS' : 'FAIL'} #{c[:name]}#{' (advisory)' if ADVISORY.include?(c[:check])}"
    end.join("\n")
  end

  # The only channel out of the roast subprocess is its output streams:
  # ExecuteInstructionJob streams them line-by-line into Rails.logger and keeps
  # nothing else. A prefixed single-line JSON record lets the job reconstruct
  # which check failed without parsing human-readable log text (or, worse,
  # reading by line position). Roast wraps every line a cog prints in its own
  # log format before it reaches the job — VerifyReport is the matching side.
  SENTINEL_PREFIX = VerifyReport::PREFIX

  def self.sentinel(result, stage:, attempt: 1, applied: nil)
    record = {
      stage: stage,
      attempt: attempt,
      checks: result[:checks].map do |c|
        entry = { check: c[:check], name: c[:name], passed: c[:passed], advisory: ADVISORY.include?(c[:check]), ms: c[:ms] }
        entry[:error] = cap_error(c[:output]) unless c[:passed]
        entry[:failing_routes] = c[:failing_routes] if c.key?(:failing_routes)
        entry
      end
    }
    record[:applied] = applied if applied
    "#{SENTINEL_PREFIX} #{JSON.generate(record)}"
  end

  def self.perform(check, workspace, known_failing_routes: [])
    case check
    when :bundle_check
      run_cmd(workspace, "bundle check", :bundle_check, "bundle check")
    when :db_prepare
      run_cmd(workspace, "bin/rails db:prepare", :db_prepare, "db:prepare")
    when :zeitwerk_check
      run_cmd(workspace, "bin/rails zeitwerk:check", :zeitwerk_check, "zeitwerk check")
    when :route_smoke
      with_route_smoke_installed(workspace, known_failing_routes) do |dir|
        result = run_cmd(workspace, "bin/rails test #{ROUTE_SMOKE_DIR}/route_smoke_test.rb", :route_smoke, "route smoke")
        result.merge(failing_routes: RouteSmoke.read_paths(File.join(dir, RouteSmoke::FAILING_FILE)))
      end
    when :rails_test
      return nil if Dir.glob("#{workspace}/test/**/*_test.rb").empty?
      run_cmd(workspace, "bin/rails test", :rails_test, "rails test")
    end
  end

  def self.with_route_smoke_installed(workspace, known_failing_routes)
    dir = File.join(workspace, ROUTE_SMOKE_DIR)
    FileUtils.mkdir_p(dir)
    ROUTE_SMOKE_FILES.each { |src, dst| FileUtils.cp(File.join(__dir__, src), File.join(dir, dst)) }
    File.write(File.join(dir, RouteSmoke::KNOWN_FAILING_FILE), known_failing_routes.join("\n"))
    yield dir
  ensure
    FileUtils.rm_rf(dir)
  end

  def self.run_cmd(workspace, cmd, check, name)
    started = Process.clock_gettime(Process::CLOCK_MONOTONIC)
    output = with_clean_bundler_env { `cd #{Shellwords.escape(workspace)} && #{cmd} 2>&1` }
    { check: check, name: name, passed: $?.success?, output: output,
      ms: ((Process.clock_gettime(Process::CLOCK_MONOTONIC) - started) * 1000).round }
  end

  # Roast runs under `bundle exec`, which sets BUNDLE_GEMFILE to the generator's
  # Gemfile and RUBYOPT=-rbundler/setup. Subprocess `bundle check` / `bin/rails`
  # against the workspace must not see those, or they resolve against the wrong
  # bundle. Bundler.with_unbundled_env removes them — but it removes EVERY
  # BUNDLE_* variable, the image-level ones included (this comment used to claim
  # otherwise; production disproved it on 2026-09-03). Without BUNDLE_PATH,
  # Bundler looks under $GEM_HOME/gems instead of $BUNDLE_PATH/ruby/<abi>/gems
  # and reports the whole lockfile missing; without BUNDLE_WITHOUT it wants the
  # development group the image never installs. Both are restored here from the
  # env as it was before `bundle exec`. In dev neither is set, so nothing is
  # added. The claude wrapper in the Dockerfile does the same for the agent,
  # which roast spawns unbundled as well.
  IMAGE_BUNDLER_ENV = %w[BUNDLE_PATH BUNDLE_WITHOUT].freeze

  def self.with_clean_bundler_env
    Bundler.with_unbundled_env do
      original = Bundler.original_env
      IMAGE_BUNDLER_ENV.each { |key| ENV[key] = original[key] if original.key?(key) }
      yield
    end
  end
end
