# frozen_string_literal: true

# Hardcoded plans for the spike. In production the plan is generated by the LLM (W1.3).
# Each plan = list of revisions. Each revision: summary (commit msg) + prompt (for Claude CLI).

module Plans
  TODO_LIST = [
    {
      summary: "Add Todo model with title, body, done, category",
      prompt: <<~PROMPT
        Create a Todo model with fields:
        - title (string, required)
        - body (text, optional)
        - done (boolean, default false)
        - category (string, optional)

        Requirements:
        - Migration with appropriate types and indexes
        - Validations in the model (title required, minimum length 1)
        - Fixtures in test/fixtures/todos.yml (at least 2 records)
        - Model test in test/models/todo_test.rb (validation test)
        - Run `bin/rails db:migrate` after creating the migration

        Do not add controllers or views — that's the next step.
      PROMPT
    },
    {
      summary: "Add TodosController with index/show/new/create/edit/update/destroy",
      prompt: <<~PROMPT
        Create a full REST controller TodosController with actions: index, show, new, create, edit, update, destroy.

        Requirements:
        - `resources :todos` in config/routes.rb
        - Strong parameters (title, body, done, category)
        - Flash messages after create/update/destroy
        - Redirects after mutations (to index or show)
        - Controller test in test/controllers/todos_controller_test.rb covering all actions
        - Do not create views yet — index/show/new/edit may return empty HTML for now
        - All controller tests must pass (bin/rails test)

        Root route can stay as it was — do not change `root`.
      PROMPT
    },
    {
      summary: "Add Tailwind views for Todo with Hotwire Turbo",
      prompt: <<~PROMPT
        Add Tailwind views for Todo with Hotwire Turbo Frames and Turbo Streams.

        Requirements:
        - app/views/todos/index.html.erb — list of todos in a table or cards, styled with Tailwind
        - app/views/todos/show.html.erb — details with edit/destroy links
        - app/views/todos/new.html.erb + edit.html.erb — forms (shared _form partial)
        - app/views/todos/_todo.html.erb partial — one todo item
        - Turbo Frame `dom_id(@todo)` for optimistic updates
        - "done" checkbox toggles via Turbo Stream (optional — if easy)
        - Status badge: green "Done" vs gray "Todo"
        - Working navigation header with a link to /todos
        - Root route to TodosController#index (change config/routes.rb)
        - Controller tests must still pass

        Do not install new gems. Use what's there (Tailwind, Turbo installed via `rails new --css tailwind`).
      PROMPT
    }
  ].freeze

  # Plan with a forced verification error — for testing the remediation loop (W2.R).
  # The prompt contains a CONTRADICTION: model validation vs. test expectation.
  # Claude implements exactly what's written → `rails test` fails → W2 enters
  # remediation scope with a real assertion error and must reconcile the conflict.
  FORCE_REMEDIATION = [
    {
      summary: "Add Product model (price validation with contradictory test)",
      prompt: <<~PROMPT
        Create a Product model with fields:
        - name (string, required)
        - price_cents (integer, required)

        Implement EXACTLY the requirements below, even if they seem contradictory.
        Do not correct, do not interpret — do literally what's written:

        1. Migration and model with the fields above.
        2. In the model ADD the validation: `validates :price_cents, numericality: { greater_than_or_equal_to: 100 }`
        3. `bin/rails db:migrate`
        4. Test in `test/models/product_test.rb` — MUST contain THIS test (literally, word for word):

           ```ruby
           test "accepts low prices for promotional products" do
             product = Product.new(name: "Widget", price_cents: 50)
             assert product.valid?, "Expected low-price product to be valid, got: \#{product.errors.full_messages}"
           end
           ```

        5. At the end run `bin/rails test`.

        Do not "fix in advance" the contradiction between the validation and the test —
        write both literally as above. If verify fails, you'll get the errors
        in the next step and then decide what to do.
      PROMPT
    }
  ].freeze

  def self.fetch(name)
    const_name = name.to_s.upcase.tr("-", "_")
    const_get(const_name)
  rescue NameError
    raise ArgumentError, "Unknown plan: #{name.inspect}. Available: #{available.join(", ")}"
  end

  def self.available
    constants.map { |c| c.to_s.downcase.tr("_", "-") }
  end
end
